name: ci-run-pytest

on:  [push]
    
jobs:
  run-tests:
    name: "Run tests in multiple environments"
    strategy:
      fail-fast: false
      matrix:
        environment: [test311, test312, test313, test314]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: prefix-dev/setup-pixi@v0.9.0
        with:
          pixi-version: v0.49.0
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          environments: ${{ matrix.environment }}

      - name: Run tests
        run: pixi run -e ${{ matrix.environment }} pytest tests -n auto
        if: steps.cache.outputs.cache-hit != 'true'
        